### ISSUE TITLE
Errors when I try to WatchStart {command}

### ISSUE THREAD

**Issue by jhoffmann** [Makaze/watch.nvim#5]
![image](https://github.com/Makaze/watch.nvim/assets/385627/8be636f1-9b08-4121-b5bd-596bd028b478)

That's after `:WatchStart erd`, but I've tried a bunch of commands including ls with the same issue.

**Comment by Makaze** [comment]
What version of Neovim are you using?

**Comment by jhoffmann** [comment]
> What version of Neovim are you using?

❯ nvim -v
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"


With kickstart, and all Lazy plugins have been updated.

**Comment by Makaze** [comment]
I advertise the plug-in as only supporting 0.10+. I can see about adding backwards compatibility, but I can't guarantee it is possible with the async functionality.

**Comment by Makaze** [comment]
Backwards compatibility was added with PR #6. Did this solve your issue?

**Comment by BaconIsAVeg** [comment]
Yes! Thanks.

**Comment by Makaze** [comment]
Awesome! Closing.
