### ISSUE TITLE
Split opens on the left even if set to "right"

### ISSUE THREAD

**Issue by Froloket64** [Makaze/watch.nvim#9]
I noticed that for me the new window opens up on the left, even though I've set it to open on the right in the config:
```lua
{
  split = {
    enabled = true,
    position = "right",
    focus = true,
  }
}
```
For other `position`s it seems to be working.

Using the latest version available through `Packer.nvim` (pretty sure it's the latest commit).

**Comment by Makaze** [comment]
I'm unable to replicate this using Lazy.nvim.

Please provide:

- Neovim version?
- watch.nvim version?
